### ISSUE TITLE
Failure to launch "Error: Set $EDITOR on your shell."

### ISSUE THREAD

**Issue by metamonsta** [Section9Labs/Cartero#30]
System Details:

cyborg@cyborg:/opt/Cartero/bin$ uname -r
3.16.0-28-generic
cyborg@cyborg:/opt/Cartero/bin$ lsb_release -r
Release:	14.04

Error::
cyborg@cyborg:/opt/Cartero/bin$ sudo ./cartero Cloner https://www.facebook.com
[sudo] password for cyborg: 
Error: Set $EDITOR on your shell.
cyborg@cyborg:/opt/Cartero/bin$ sudo ./cartero --editor
Error: Set $EDITOR on your shell.
cyborg@cyborg:/opt/Cartero/bin$ sudo ./cartero --help
Error: Set $EDITOR on your shell.
cyborg@cyborg:/opt/Cartero/bin$ sudo ./cartero WebMailer -S webmail -D ~/sample.json -b ../templates/mail/sample.web -r cartero@gmail.com
Error: Set $EDITOR on your shell.
cyborg@cyborg:/opt/Cartero/bin$ 

Please advise

**Comment by FreedomCoder** [comment]
Not sure how you installed cartero. But as the error states you need to 
```bash
cyborg@cyborg:/opt/Cartero/bin$ export EDITOR=vim
```
The easiest way to fix this is to add it on your ~/.bashrc or ~/.profile or ~/.bash_profile. 
```sh
export EDITOR=vim
```

**Comment by FreedomCoder** [comment]
Also, another way to fix this if you want to do in Cartero is to use the ~/.cartero/config  file created and add:
```json
{
    "editor" : "vim",
    "metasploit" : { 
    ...
    }
}

**Comment by metamonsta** [comment]
thx, 2nd option worked.

My initial attempts to set the editor to nano via export didnt. Directly adding it to the config has me up and running. 

+1

**Comment by FreedomCoder** [comment]
Awesome to hear ! It was always an option, not just documented. Now, the installation script, will add vim by default to the configuration script and it will get overwrite by EDITOR and/or if you change the config.

**Comment by metamonsta** [comment]
i heart your geeksta. thanks a million all
