### ISSUE TITLE
Failed to connect to a master node at localhost 27017

### ISSUE THREAD

**Issue by elbns** [Section9Labs/Cartero#38]
Hi,

I got this error ("Failed to connect to a master node at localhost:27017") when launching `bin/cartero -d Listener --webserver /tmp/templateXX_com -p 8080`

Here is my **~/.cartero/logs/mongodb.log** : 
Mon Mar 23 17:46:55 Mongo DB : starting : pid = 2939 port = 27017 dbpath = ~/.cartero/data/db
Mon Mar 23 17:46:55 db version v1.4.4, pdfile version 4.5
Mon Mar 23 17:46:55 git version: nogitversion
Mon Mar 23 17:46:55 sys info: Linux bobek-a0 2.6.32-trunk-[...]
Mon Mar 23 17:46:55 waiting for connections on port 27017
Mon Mar 23 17:46:55 web admin interface listening on port 28017
Mon Mar 23 17:46:56 connection accepted from 127.0.0.1:39531 #1
Mon Mar 23 17:46:56 end connection 127.0.0.1:39531

`$ ps -ef | grep "mongo"`
my_user 29139     1  0 17:46 ?        00:00:00 mongod --fork --dbpath=/home/my_user/.cartero/data/db --logpath=/home/my_user/.cartero/logs/mongodb.log --bind_ip localhost --port 27017 --logappend

Do you have any idea ?

**Comment by FreedomCoder** [comment]
Could you also include the full output from bin/cartero ?

**Comment by elbns** [comment]
`$ bin/cartero -d Listener --webserver /tmp/odas_fr  -p 8080`
Failed to connect to a master node at localhost:27017
/usr/local/rvm/gems/ruby-2.1.5/gems/mongo-1.12.0/lib/mongo/mongo_client.rb:417:in connect'
/usr/local/rvm/gems/ruby-2.1.5/gems/mongo-1.12.0/lib/mongo/mongo_client.rb:656:in setup'
/usr/local/rvm/gems/ruby-2.1.5/gems/mongo-1.12.0/lib/mongo/mongo_client.rb:179:in initialize'
/usr/local/rvm/gems/ruby-2.1.5/gems/mongo-1.12.0/lib/mongo/legacy.rb:52:in initialize'
/home/my_user/phishing/Cartero/lib/cartero/commands/listener.rb:118:in new'
/home/my_user/phishing/Cartero/lib/cartero/commands/listener.rb:118:in block in setup'
/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.5/lib/sinatra/base.rb:1402:in configure'
/home/my_user/phishing/Cartero/lib/cartero/commands/listener.rb:116:in setup'
/home/my_user/phishing/Cartero/lib/cartero/command.rb:83:in block in method_added'
/home/my_user/phishing/Cartero/lib/cartero/cli.rb:189:in block in run'
/home/my_user/phishing/Cartero/lib/cartero/cli.rb:183:in each'
/home/my_user/phishing/Cartero/lib/cartero/cli.rb:183:in run'
bin/cartero:52:in <main>'

**Comment by FreedomCoder** [comment]
Did you try to connect directly to it ?
```ruby
require 'active_support'
require 'mongo_mapper'
# if it fails here. There is an issue w/ mongodb. I would double check your permissions. 
::MongoMapper.connection = ::Mongo::Connection.new("localhost", 27017) 
::MongoMapper.database = "Cartero"

db = MongoMapper.database
db.collection("hits") # This should return something

```

Also, if you want to start the DB alone you can do so with:

```shell
bin/cartero Mongo --start
```
and then stop it with:
```shell
bin/cartero Mongo --stop

**Comment by elbns** [comment]
Thanks for your help, it looks like a permission problem on my mongoDB.

I will keep you informed.

**Comment by FreedomCoder** [comment]
Thank you. Let me know if you can fix it, otherwise, we can keep on looking into this. 

I was also searching into Mongodb 1.4.4 and newer versions of mongo_mapper I saw some people having issues online. If that is the case, I might have to clarify a minimun version of mongodb and mongo_mapper.

**Comment by FreedomCoder** [comment]
Closing this issue. Please re-open if necessary.

**Comment by elbns** [comment]
Updating mongoDB to 3.0 solved the problem ! Thanks again for your help.
