### ISSUE TITLE
Webserver Error

### ISSUE THREAD

**Issue by mehranexpert** [Section9Labs/Cartero#63]
NameError at /
uninitialized constant Rack::Head::REQUEST_METHOD

    file: head.rb
    location: call
    line: 15

**Comment by FreedomCoder** [comment]
Hey could you provide a little more info :-)

**Comment by mehranexpert** [comment]
i just install it on kali , and run Listener webserver and Here is my terminal  ::

http://pastebin.com/Zr5iSgt5

**Comment by FreedomCoder** [comment]
Thanks this is much better. I'll have an answer for you tomorrow hopefully. Currently on a plane and about to land :-)

**Comment by mehranexpert** [comment]
Have a Safe Trip :)

**Comment by FreedomCoder** [comment]
Sorry for the late response, but I honestly cannot reproduce this. Which versions of gems you are using ?

**Comment by FreedomCoder** [comment]
I am using Rack 1.6.4 and Puma 3.4.0 and I do not get the same error message.  Could you perform a bundle update and see if you still get the same error ?

**Comment by FreedomCoder** [comment]
closing ticket for lack of interaction.

**Comment by AbhishekShah212** [comment]
I had the same issue. For some reason, Rack 1.6.4 breaks Cartero on Kali Linux. I ended up using Rack 1.5.3. Run these commands to solve your problem:
 
gem uninstall rack
(Press whichever number corresponds to Rack 1.6.4)

**Comment by FreedomCoder** [comment]
Interésting Thanks for this feedback
