### ISSUE TITLE
Credentials Harvester Not Working as Expected

### ISSUE THREAD

**Issue by AbhishekShah212** [Section9Labs/Cartero#65]
Hey, 

I've been having this issue where I can only harvest credentials from specific sites (facebook, twitter). Some sites I try have failed to harvest credentials (like login.microsoftonline.com). Is Cartero looking for specific id's in the HTML to determine what are credentials ? 

I would really appreciate the help. 

Hope you have a good weekend.

**Comment by FreedomCoder** [comment]
@AbhishekShah212  Yes Cartero has that logic build into it, but if you click on the event it will show you the entire content of the post request. So you should be able make it work. Additionally, the Cloner app is not perfect. So if you find a site for which you find it does not work, it is always good to know if this is something that needs custom work on top of it and/or it is something that Cartero could add to its default logic.

**Comment by AbhishekShah212** [comment]
I'll definitely look into customizing it, then. In reference to your statement that "if you click on the event, it will show you the entire content of the post request", where would I find that information? In the AdminWeb Console? In the Server output when I use the listener (if it is this one, I never see anything about user name/password)

**Comment by FreedomCoder** [comment]
@AbhishekShah212 The adminWeb should show you that information. Remember that if you running this on a remote server AdminWeb only works on Localhost by default. You will have to expose the server and I WILL HIGHLY RECOMMEND YOU LIMIT ACCESS WITH IPTABLES to only your IP. It is currently a TODO to implement authentication for the AdminWeb in a secure manner.

**Comment by AbhishekShah212** [comment]
Hahaha, yes I understand. Thanks for the info. I have been unable to find the information as I just checked all over. I did find where to edit the Cloner "credentials" regex in sinatra_helpers.rb

**Comment by FreedomCoder** [comment]
Sounds good. Also feel free to submit a patch if you found a site that is not contemplated by the regex but is mainstream like login.microsoftonline.com

**Comment by AbhishekShah212** [comment]
Will do, thanks again and have a great weekend!
