### ISSUE TITLE
Linkedin Oauth

### ISSUE THREAD

**Issue by AbhishekShah212** [Section9Labs/Cartero#66]
Hope you had a great weekend. 

I tried to use the LinkedIn Module, and I have been unable to get the oauth_token and the oauth_secret. I have gotten the api_access, the api_secret, and the access_token. That said, where does the oauth_token and oauth_secret come in? Terminology with OAuth is rather ambiguous, so I was hoping you could clarify. Is it perhaps that oauth_token and o_auth secret were deprecated with the Advent of OAuth 2?

I have been working on the patch for the credential harvesting to expand to a site like login.microsoftonline.com by the way!
```json
{
  "name": "<%= @name %>",
  "type": "<%= @type %>",
	"options": {
	  "api_access": "<%= @api_access %>",
	  "api_secret": "<%= @api_secret %>",
	  "oauth_token": "<%= @oauth_token %>",
	  "oauth_secret": "<%= @oauth_secret %>"
	}   
}
```

**Comment by FreedomCoder** [comment]
Yes you are correct. I think this might be a valid  Feature Request to move to oauth2. If LinkedIn is still supporting Oauth you should follow this steps. 

https://github.com/hexgnu/linkedin/blob/master/EXAMPLES.md

**Comment by AbhishekShah212** [comment]
It is, thanks so much! Should be set.
